apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\michel\AppData\Local\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\michel\AppData\Local\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - args:
            - sh
            - -c
            - uvicorn main:app --reload --host 0.0.0.0
          env:
            - name: ORDERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: ORDERS_SERVICE_URL
                  name: gateway-env
            - name: USERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: USERS_SERVICE_URL
                  name: gateway-env
          image: baranbartu/k-api-gateway:latest
          name: gateway
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: gateway-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: gateway-cm0
          name: gateway-cm0
