apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\michel\AppData\Local\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\michel\AppData\Local\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: users
    spec:
      containers:
        - args:
            - sh
            - -c
            - uvicorn main:app --reload --host 0.0.0.0
          image: baranbartu/k-users:latest
          name: users
          volumeMounts:
            - mountPath: /app
              name: users-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: users-cm0
          name: users-cm0
